sudo: false
language: ruby
rvm:
- 2.4.2
cache: bundler
script:
- bundle exec rake spec && bundle exec codeclimate-test-reporter
git:
  depth: false
install:
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch --tags
- bundle install --jobs=3 --retry=3
notifications:
  slack:
    secure: Op5mXwJvA1KlML5VrEfQDQOP46ArkgfXDPOh8ktV7tfTGmiL7FzT0Eu29kRHKuk8K/BjT6V6YDR/y+MMICCS2/2XLFzcXEYnnake0IelnLNZZQ/pi9w46PqCTlamGabz2yqLeoma8qH7YaqzgZ+5Oi6mSVhUVqfejsi+ySfrcmJPMnKgcVEdJw0iSaKkaMs+Ub4kyDsFZEzv2HAqCrUOJDl5ps3Mjltl3ioD4lW3AZ+P4sfURfMssz+tZR2OfMXKIWYuCFP4ljHx56crTku9yvrikZOUOWc0GHpUEtsesWCYHGuC5tivEBnEKHWPmSa4A93uOOGGnYIz4Z9vCtbvsTS9UUcQZXSt+2/FdkvOLr3hONboz3yqqlT83+wYkjxPtaHFL5pPGbCm3oOSvTnv0IjcQlHymjtZpddc0cohQvcHQlqiimH7k72Gqn5RL+NFDS7nbvfNIWk49P1x5Zg8facIj1DDvseO2OgE2IVAeNAp3q2zcQKf643L756iez7+b45idCnh5w9VNTdQHlQchtyca5vCwJOlwYpDzJ+N/DcemARiFK8lktkzV7A1DPnNjB2lh9lNujt7zoFgpf2g0fti1tAF72v8HANSksYLwIldhlstdX3uSTa9ILi9PtZnu5e12vH/3kqOG7j7aq8mC7bj09L4AqztIJebDBGZulA=
